default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  database: jira_clone_development
  username: jira_db
  password: 12345
  host: localhost
  port: 5432
  <<: *default

test:
  database: jira_clone_test
  username: jira_db
  password: 12345
  <<: *default