default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: jira_clone_development
  username: postgres
  password: <%= ENV['JIRA_CLONE_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: jira_clone_test